apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: robot-shop-gcp
description: main application pipeline
serialPipeline:
 stages:
 - targetId: dev
   profiles: [dev]
 - targetId: prod
   profiles: [prod]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: dev
description: development namespace
gke:
 cluster: projects/coe-srs-2022/locations/us-central1-c/clusters/srs-cluster

---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: prod
description: production cluster
requireApproval: true
gke:
 cluster: projects/coe-srs-2022/locations/us-central1-c/clusters/srs-cluster